<a href="https://colab.research.google.com/github/keerthimareedu3/keerthi/blob/main/LIBRARIES_practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.NUMPY**


In [3]:
import numpy as np
n=[10,11,12,13,14,15,16,17,18,19,20]
g=np.array(n)
print(g)
print(g.sum())
print(g.mean())
print(g.min())
print(g.max())

[10 11 12 13 14 15 16 17 18 19 20]
165
15.0
10
20


In [6]:
import numpy as np
k=[212,233,465,342,454,243,234]
values=np.array(k)
average_tem=np.mean(values)
above_avg=values[values>average_tem]
print(values)
print(values.mean())
print(above_avg)
print(values.max())

[212 233 465 342 454 243 234]
311.85714285714283
[465 342 454]
465


In [24]:
import numpy as np
h=([[22,25,24],
   [23,24,25],
   [20,24,25],
   [24,25,22],
   [21,25,24]])
k=np.array(h)
p=np.mean(h,axis=1)
l=np.max(h,axis=0)
m=np.sum(h,axis=1)
n=np.argmax(m)
print("STUDENTS MARKS",k)
print("MEANS OF STUDENTS MARKS",p)
print("SUBJECT-WISE HIGESTEST MARKS",l)
print("SUM OF MARKS",m)
print("OVERALL TOPPER",n+1)


STUDENTS MARKS [[22 25 24]
 [23 24 25]
 [20 24 25]
 [24 25 22]
 [21 25 24]]
MEANS OF STUDENTS MARKS [23.66666667 24.         23.         23.66666667 23.33333333]
SUBJECT-WISE HIGESTEST MARKS [24 25 25]
SUM OF MARKS [71 72 69 71 70]
OVERALL TOPPER 2


In [27]:
import numpy as np
l=[23,25,26,25,24]
k=[33,35,37,38,39]
t=np.array(l)
q=np.array(k)
u=(t+q)
v=(t-q)
w=(t*q)
x=(t/q)
print("ADDITION",u)
print("SUBTRACTION",v)
print("MULTIPLICATION",w)
print("DIVISION",x)

ADDITION [56 60 63 63 63]
SUBTRACTION [-10 -10 -11 -13 -15]
MULTIPLICATION [759 875 962 950 936]
DIVISION [0.6969697  0.71428571 0.7027027  0.65789474 0.61538462]


# **2.PANDAS**

In [30]:
import pandas as pd
data={
    "Stundent_Name":["keerthi","kavya","harshi","navya"],
    "Maths":[25,24,23,22],
    "Science":[21,25,23,22],
    "English":[22,24,25,21]
}
df=pd.DataFrame(data)
print(df)
print(df.head(3))
print(df.tail(2))

  Stundent_Name  Maths  Science  English
0       keerthi     25       21       22
1         kavya     24       25       24
2        harshi     23       23       25
3         navya     22       22       21
  Stundent_Name  Maths  Science  English
0       keerthi     25       21       22
1         kavya     24       25       24
2        harshi     23       23       25
  Stundent_Name  Maths  Science  English
2        harshi     23       23       25
3         navya     22       22       21


In [34]:
import pandas as pd
data={
    "Stundent_Name":["keerthi","kavya","harshi","navya"],
    "Maths":[25,24,23,22],
    "Science":[21,25,23,22],
    "English":[22,24,25,21]
}
df=pd.DataFrame(data)
df["total"]=df[["Maths","Science","English"]].sum(axis=1)
df["average"]=df[["Maths","Science","English"]].mean(axis=1)
print(df)
print(df["total"])
print(df["average"])

  Stundent_Name  Maths  Science  English  total    average
0       keerthi     25       21       22     68  22.666667
1         kavya     24       25       24     73  24.333333
2        harshi     23       23       25     71  23.666667
3         navya     22       22       21     65  21.666667
0    68
1    73
2    71
3    65
Name: total, dtype: int64
0    22.666667
1    24.333333
2    23.666667
3    21.666667
Name: average, dtype: float64


In [48]:
import pandas as pd
data={
   "Stundent_Name":["keerthi","kavya","harshi","navya"],
    "Maths":[85,87,75,79],
    "Science":[21,25,23,22],
    "English":[22,24,25,21]
    }
df=pd.DataFrame(data)
df2=df["Maths"]>80
df3=df[["Maths","Science","English"]].mean(axis=1)
df4=(df[df3>75])
print(df)
print(df2)
print(df3)
print(df4)


  Stundent_Name  Maths  Science  English
0       keerthi     85       21       22
1         kavya     87       25       24
2        harshi     75       23       25
3         navya     79       22       21
0     True
1     True
2    False
3    False
Name: Maths, dtype: bool
0    42.666667
1    45.333333
2    41.000000
3    40.666667
dtype: float64
Empty DataFrame
Columns: [Stundent_Name, Maths, Science, English]
Index: []
