<a href="https://colab.research.google.com/github/keerthimareedu3/keerthi/blob/main/MACHINE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FIT_TRANSFORM(p)**

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
d={
    "names":["KEERTHI","HARSHI","NAVYA","KAVYA","SRILATHA"],
    "location":["HYD","KHMM","KDD","HYD","KDD"]
  }
df=pd.DataFrame(d)
print("NOMRAL DATAFRAME",)
print(df)
label_encoder=LabelEncoder()
df["NAMES"]=label_encoder.fit_transform(df['names'])
df["LOCATION"]=label_encoder.fit_transform(df["location"])
print()
print("TRANSFORM DATAFRAME",)
print(df)

NOMRAL DATAFRAME
      names location
0   KEERTHI      HYD
1    HARSHI     KHMM
2     NAVYA      KDD
3     KAVYA      HYD
4  SRILATHA      KDD

TRANSFORM DATAFRAME
      names location  NAMES  LOCATION
0   KEERTHI      HYD      2         0
1    HARSHI     KHMM      0         2
2     NAVYA      KDD      3         1
3     KAVYA      HYD      1         0
4  SRILATHA      KDD      4         1


In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
k={
    "items":["mobile","laptop","washmachine","fridge"],
    "brand_names":["apple","HP","samsung","haier"],
    "prices":[1000000,50000,25000,30000]
}
df=pd.DataFrame(k)
print("NORMAL DATAFRAME")
print(df)
data=LabelEncoder()
df["ITEMS"]=data.fit_transform(df["items"])
df["BRAND_NAMES"]=data.fit_transform(df["brand_names"])
df["PRICES"]=data.fit_transform(df["prices"])
print()
print("TRANSFORM DATAFRAME")
print(df)

NORMAL DATAFRAME
         items brand_names   prices
0       mobile       apple  1000000
1       laptop          HP    50000
2  washmachine     samsung    25000
3       fridge       haier    30000

TRANSFORM DATAFRAME
         items brand_names   prices  ITEMS  BRAND_NAMES  PRICES
0       mobile       apple  1000000      2            1       3
1       laptop          HP    50000      1            0       2
2  washmachine     samsung    25000      3            3       0
3       fridge       haier    30000      0            2       1


In [ ]:
from google.colab import files
uploaded=files.upload()


Saving sales31.csv to sales31.csv


In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
df=pd.read_csv("sales31.csv")
sales=LabelEncoder()
df["ORDER_ID"]=sales.fit_transform(df["ord id"])
df["CUSTOMER_NAME"]=sales.fit_transform(df["cust name"])
df["CUSTOMER_ID"]=sales.fit_transform(df["cust id"])
df["PRODUCT_NAME"]=sales.fit_transform(df["prod name"])
df["PRODUCT_COST"]=sales.fit_transform(df["prod cost"])
print(df)


   ord id   cust name  cust id                   prod name  prod cost  \
0  192837       Veeru        3                   LG Mobile      65999   
1  192838     Neelima       19        Apple iPad 10.2-inch      63000   
2  192839      Balaji       12      34in Ultrawide Monitor      75999   
3  192840      Shahid       20                   iPhone 11      60000   
4  192841       Vinay       10  Bose SoundSport Headphones      69999   
5  192842       Vinay       10                20in Monitor      65999   
6  192843      Balaji       12                    iPhone 8      55999   
7  192844  Nireekshan        1      27in 4K Gaming Monitor      55999   
8  192845        Venu       23                    iPhone 9      55999   
9  192846       Veeru        3                20in Monitor      63000   

   ORDER_ID  CUSTOMER_NAME  CUSTOMER_ID  PRODUCT_NAME  PRODUCT_COST  
0         0              4            1             5             3  
1         1              1            4             3  

# **MinMaxScaler**

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
d={
    "x":["keerthi","harshi","navya","kavya","kussu"],
    "y":[4,65,80,120,150]
   }
df=pd.DataFrame(d)
data=MinMaxScaler()
print(df)
values=data.fit_transform(df[["y"]])
print(values)

         x    y
0  keerthi    4
1   harshi   65
2    navya   80
3    kavya  120
4    kussu  150
[[0.        ]
 [0.41780822]
 [0.52054795]
 [0.79452055]
 [1.        ]]


In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

d = {
        "x" : [10, 20, 30, 40, 50],
        "y" : [25, 50, 75, 100, 125]
}

df = pd.DataFrame(d)
mm_scale = MinMaxScaler(feature_range = (0, 1))

print(df)

df[["x", "y"]] = mm_scale.fit_transform(df[["x", "y"]])
print(df)

    x    y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125
      x     y
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00


In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
h={
    "k":[25,50,75,100,125,150],
    "l":[50,100,150,200,250,300]
}
df=pd.DataFrame(h)
values=MinMaxScaler(feature_range = (0, 1))
print(df)
df[["k","l"]]=values.fit_transform(df[["k","l"]])
print(df)

     k    l
0   25   50
1   50  100
2   75  150
3  100  200
4  125  250
5  150  300
     k    l
0  0.0  0.0
1  0.2  0.2
2  0.4  0.4
3  0.6  0.6
4  0.8  0.8
5  1.0  1.0


# **FUNCTIONTRANSFORMER**

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

a = [[10, 20], [30, 40], [50, 60]]

f = np.array(a)

def add_ten(x):
 return x + 10

obj = FunctionTransformer(add_ten)

result = obj.transform(f)

print(f)
print()
print(result)

[[10 20]
 [30 40]
 [50 60]]

[[20 30]
 [40 50]
 [60 70]]


In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
k=[[35,43],[45,56],[67,78]]
f=np.array(k)
def add_ten(x):
  return x+10
object=FunctionTransformer(add_ten)
result=object.transform(f)
print(f)
print()
print(result)

[[35 43]
 [45 56]
 [67 78]]

[[45 53]
 [55 66]
 [77 88]]


In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
k=[[23,65,76],[253,5453,342]]
l=np.array(k)
def sub(x):
  return x-10
values=FunctionTransformer(sub)
results=values.transform(l)
print("original matrix")
print(l)
print("transformer matrix")
print(results)

original matrix
[[  23   65   76]
 [ 253 5453  342]]
transformer matrix
[[  13   55   66]
 [ 243 5443  332]]


In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
o=[[325465,23546578,243546578,2435678,24332546]]
p=np.array(o)
def div(x):
  return x/100
data=FunctionTransformer(div)
values=data.transform(p)
print("original matrix")
print(o)
print("transformer matrix")
print(values)


original matrix
[[325465, 23546578, 243546578, 2435678, 24332546]]
transformer matrix
[[   3254.65  235465.78 2435465.78   24356.78  243325.46]]


# ***OUTLIER***

In [ ]:
import numpy as np
import pandas as pd
sales=pd.DataFrame()
sales["products"]=["moblie","t.v","laptop","fridge","washmachine"]
sales["prices"]=[25000,50000,60000,75000,30000]
sales["with_dicount"]=[24500,49500,59500,74500,29500]
values=sales["prices"]>50000
print(sales)
new=sales[values]
print(new)

      products  prices  with_dicount
0       moblie   25000         24500
1          t.v   50000         49500
2       laptop   60000         59500
3       fridge   75000         74500
4  washmachine   30000         29500
  products  prices  with_dicount
2   laptop   60000         59500
3   fridge   75000         74500


In [ ]:
import numpy as np
import pandas as pd
student=pd.DataFrame()
student["names"]=["navya","bavya","kavya","keerthi"]
student["id"]=[25,45,23,56]
student["branch"]=["CSE","EEE","ECE","CIVIL"]
data=student["id"]<50
print(student)
new_data=student[data]
print(new_data)

     names  id branch
0    navya  25    CSE
1    bavya  45    EEE
2    kavya  23    ECE
3  keerthi  56  CIVIL
   names  id branch
0  navya  25    CSE
1  bavya  45    EEE
2  kavya  23    ECE


In [45]:
import numpy as np
import pandas as pd
values= pd.DataFrame()
values["price"]=[32434,243254,4365,325465,2436547]
values["actual_prices"]=[12435465,3465767,2347576,454657,4567456]
data=values["price"]<100000
print(values)
new_data=values[data]
print(new_data)

     price  actual_prices
0    32434       12435465
1   243254        3465767
2     4365        2347576
3   325465         454657
4  2436547        4567456
   price  actual_prices
0  32434       12435465
2   4365        2347576
