<a href="https://colab.research.google.com/github/keerthimareedu3/keerthi/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NUMPY***





In [ ]:
import numpy
print("hello")

hello


In [ ]:
import numpy as np
a=2142312
student_id=np.array(a)
print(student_id)
print(type(student_id))
print(student_id.ndim)

2142312
<class 'numpy.ndarray'>
0


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
data=np.array(a)
print(data)
print(type(data))
print(data.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
import numpy as np
emp_id=[[12,24],[34,45],[56,67]]
values=np.array(emp_id)
print(values)
print(values.ndim)
print(type(emp_id))
print(type(values))


[[12 24]
 [34 45]
 [56 67]]
2
<class 'list'>
<class 'numpy.ndarray'>


# ***ALIASING NUMPY***

In [ ]:
import numpy as np
from numpy import asarray
data=[[12,23],[34,45],[56,67],[78,89]]
values=np.asarray(data)
print(values)
print(values.ndim)
print(type(data))
print(type(values))

[[12 23]
 [34 45]
 [56 67]
 [78 89]]
2
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
from numpy import asarray
sales=[[12,34],[45,54],[67,76]]
details=np.asarray(sales)
print(sales)
print(details)
print(type(sales))
print(type(details))
print(details.ndim)


[[12, 34], [45, 54], [67, 76]]
[[12 34]
 [45 54]
 [67 76]]
<class 'list'>
<class 'numpy.ndarray'>
2


In [ ]:
import numpy as np
from numpy import asarray
number=[[123,333,333],[333,3333,33333]]
values=np.asarray(number)
print(number)
print(values)
print(type(number))
print(type(values))
print(values.ndim)


[[123, 333, 333], [333, 3333, 33333]]
[[  123   333   333]
 [  333  3333 33333]]
<class 'list'>
<class 'numpy.ndarray'>
2


# ***INDEXING IN NUMPY***

In [ ]:
import numpy as np
sales=[[12,23,34],[45,56,67],[78,90,21]]
details=np.array(sales)
print(details[0,0])
print(details[0,1])
print(details[0,2])
print()
print(details[1,0])
print(details[1,1])
print(details[1,2])
print()
print(details[2,0])
print(details[2,1])
print(details[2,2])

12
23
34

45
56
67

78
90
21


In [ ]:
import numpy as np
values=[12,23,34,45,56,67,78,89,90]
print(values[2])
print(values[4])
print(values[6])
print(values[8])

34
56
78
90


In [ ]:
import numpy as ny
sales=[[1333333,23433453],[342323,435232]]
print(sales[1])



[342323, 435232]


# ***SLICING IN NUMPY***

In [ ]:
import numpy as np
details=[124,234,343,432,543,564,453]
print(details[0:3])
print(details[3:])
print(details[:4])
print(details[:])

[124, 234, 343]
[432, 543, 564, 453]
[124, 234, 343, 432]
[124, 234, 343, 432, 543, 564, 453]


In [ ]:
import numpy as np
values=[233,4323,33332332,4334,33223]
print(values[2:3])
print(values[:2])
print(values[3:])
print(values[:])

[33332332]
[233, 4323]
[4334, 33223]
[233, 4323, 33332332, 4334, 33223]


In [ ]:
import numpy as np
sales=[12,23,34,45,56,67,78,89]
values=np.asarray(sales)
print(values[2:5])
print(values[3:])
print(values[:5])
print(values[:])

[34 45 56]
[45 56 67 78 89]
[12 23 34 45 56]
[12 23 34 45 56 67 78 89]


# ***ZEROS(P)***

In [ ]:
import numpy as np
values=np.zeros(5)
print(values)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
sales=np.zeros(100)
print(sales)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


# ***ONES(p)***

In [ ]:
import numpy as np
data=np.ones(10)
print(data)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
sales=np.ones(1000)
print(sales)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

# ***MATRIX***

In [ ]:
import numpy as np
sales =[[12,23,34],[45,56,67],[78,89,90]]
values=np.asarray(sales)
print(sales)
print("THE MATRIX IS:")
print(values)

[[12, 23, 34], [45, 56, 67], [78, 89, 90]]
THE MATRIX IS:
[[12 23 34]
 [45 56 67]
 [78 89 90]]


In [ ]:
import numpy as np
sales=[[44,43],[76,89]]
numbers=np.asarray(sales)
print(sales)
print("THE 2*2 MATRIX IS:")
print(numbers)

[[44, 43], [76, 89]]
THE 2*2 MATRIX IS:
[[44 43]
 [76 89]]


# ***ATTRIBUTES***

1.*Shape*

In [ ]:
import numpy as np
set=[[12,23,34],[234,454,232]]
group=np.array(set)
print(group)
print(group.shape)
print(type(group))


[[ 12  23  34]
 [234 454 232]]
(2, 3)
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
values=[[23,54,67],[6556,6756,6545],[213,456,876]]
group=np.array(values)
print(group)
print(group.shape)
print(type(group))

[[  23   54   67]
 [6556 6756 6545]
 [ 213  456  876]]
(3, 3)
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
items=[[1,2],[3,4]]
sales=np.array(items)
print(sales)
print(sales.shape)

[[1 2]
 [3 4]]
(2, 2)


2.*ndim*

In [ ]:
import numpy as np
values=np.array(12)
print(values.ndim)
print(values.shape)
print(type(values))

0
()
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
details=np.array([21,34,43])
print(details)
print(details.ndim)
print(details.shape)
print(type(details))

[21 34 43]
1
(3,)
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
sales=np.array([[1232,4554,5643],[7534,8745,32421]])
print(sales)
print(sales.ndim)
print(sales.shape)
print((type(sales)))

[[ 1232  4554  5643]
 [ 7534  8745 32421]]
2
(2, 3)
<class 'numpy.ndarray'>


3.T *attribute*

In [ ]:
import numpy as np
values=np.array([[12,23],[34,45]])
print("THE MATRIX:",)
print(values)
print("THE TRANPOSE MATRIX:",)
print(values.T)
print("The number of dimensions:",values.ndim)
print("The size of matix:",values.shape)


THE MATRIX:
[[12 23]
 [34 45]]
THE TRANPOSE MATRIX:
[[12 34]
 [23 45]]
The number of dimensions: 2
The size of matix: (2, 2)


In [ ]:
import numpy as np
details=np.array([[23312,322323,34123,],[32143,45234,423445],[4312,3522,455432]])
print("THE MATRIX:")
print(details)
print("THE TRANPOSE MATIX:")
print(details.T)
print("The number of dimensions:",details.ndim)
print("The size of matix:",details.shape)

THE MATRIX:
[[ 23312 322323  34123]
 [ 32143  45234 423445]
 [  4312   3522 455432]]
THE TRANPOSE MATIX:
[[ 23312  32143   4312]
 [322323  45234   3522]
 [ 34123 423445 455432]]
The number of dimensions: 2
The size of matix: (3, 3)


In [ ]:
import numpy as np
sales=np.array([[23312,322323,34123,],[32143,45234,423445],[4312,3522,455432]])
print("THE MATRIX:")
print(sales)
print("THE TRANPOSE MATIX:")
print(sales.T)
print("The number of dimensions:",sales.ndim)
print("The size of matix:",sales.shape)

THE MATRIX:
[[ 23312 322323  34123]
 [ 32143  45234 423445]
 [  4312   3522 455432]]
THE TRANPOSE MATIX:
[[ 23312  32143   4312]
 [322323  45234   3522]
 [ 34123 423445 455432]]
The number of dimensions: 2
The size of matix: (3, 3)
